# This script is supposed to: 
# 1. create a VPC in yoru AWS account
# 2. Create subnets within the VPC and set up the route table and internet gateway
# 3. launch Spot instance
# 4. start one of multiple steps to install GPT4ALL

---
- name: Set up GPT4All on AWS
  hosts: localhost
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "your_vpc_name"
        cidr_block: "10.0.0.0/16"
        region: "us-east-1"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"
      register: vpc

    - name: Create an Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-east-1"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"
      register: igw

    - name: Create a Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-east-1"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"
      register: route_table

    - name: Create a subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "10.0.1.0/24"
        region: "us-east-1"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"
      register: subnet

    - name: Associate Route Table to Subnet
      amazon.aws.ec2_vpc_route_table:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: GPT4All Route Table
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.internet_gateway.id }}"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"

    - name: Launch Spot instance
      amazon.aws.ec2_instance:
        state: present
        key_name: "{{ keypair.key.name }}"
        instance_type: t2.micro
        image_id: ami-0c94855ba95b798c7  # Amazon Linux 2 LTS AMI (HVM)
        wait: true
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        instance_tags:
          Name: GPT4All Instance
        spot_price: "0.0075"
        aws_access_key: "access-key"
        aws_secret_key: "secret-key"
      register: ec2

    - name: Install Git
      package:
        name: git
        state: present
      delegate_to: "{{ ec2.instances[0].public_dns_name }}"

    - name: Clone GPT4All repository
      git:
        repo: 'https://github.com/nomic-ai/gpt4all.git'
        dest: '/home/ec2-user/gpt4all'
      delegate_to: "{{ ec2.instances[0].public_dns_name }}"
