---
- name: Set up GPT4All on AWS
  hosts: localhost
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "your_vpc_name"
        cidr_block: "10.0.0.0/16"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"
      register: vpc

    - name: Create an Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"
      register: igw

    - name: Create a Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"
      register: route_table

    - name: Create a subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "10.0.1.0/24"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"
      register: subnet

    - name: Associate Route Table to Subnet
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        route_table_id: "{{ route_table.route_table.id }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.gateway.id }}"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"

    - name: Launch Spot instance
      amazon.aws.ec2:
        key_name: "your_key_name"
        instance_type: "t2.micro"
        image: "ami-0c94855ba95b798c7" # Amazon Linux 2
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        group: "your_security_group_name"
        instance_tags:
          Name: "gpt4all-instance"
        wait: yes
        spot_price: "0.01"
        region: "us-west-2"
        aws_access_key: "your_access_key"
        aws_secret_key: "your_secret_key"
      register: ec2

    - name: Install Git
      package:
        name: git
        state: present
      delegate_to: "{{ ec2.instances[0].public_dns_name }}"

    - name: Clone GPT4All repository
      git:
        repo: 'https://github.com/nomic-ai/gpt4all.git'
        dest: '/home/ec2-user/gpt4all'
      delegate_to: "{{ ec2.instances[0].public_dns_name }}
